use_frameworks!

platform :ios, '11.0'

target 'razorpay-customui-pod_Example' do
  
  pod 'razorpay-customui-pod', :path => '../'

  target 'razorpay-customui-pod_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
